### ISSUE TITLE
bzr missing in golang:alpine

### ISSUE THREAD

**Issue by Pixelartist** [kafkaesque-io/pulsar-beam#58]
Hello,

while trying to build your image I encountered the following error:
```
D:\projects\pulsar\pulsar-beam (master -> origin)
λ docker build -t pulsar-beam .
Sending build context to Docker daemon  237.6kB
Step 1/13 : FROM golang:alpine AS builder
 ---> 3289bf11c284
Step 2/13 : LABEL maintainer="kafkaesque.io"
 ---> Using cache
 ---> b0b2cacac0a7
Step 3/13 : RUN apk --no-cache add build-base git bzr mercurial gcc
 ---> Running in c4cc97e18153
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  bzr (missing):
    required by: world[bzr]
The command '/bin/sh -c apk --no-cache add build-base git bzr mercurial gcc' returned a non-zero code: 1
```

I tried to check why bazaar is missing - but could not see any quick solution, therefore I tested it without bzr and was able to build the image.

Can you elaborate why bzr is needed and if fix the error?

**Comment by zzzming** [comment]
@Pixelartist bzr is not needed. Alpine package manager just pulled out bzr over the weekend. I realized that too in another our repo. It is no longer needed. Can you please help do a PR to remove `bzr`? Actually, remove these three `bzr mercurial gcc`. It was needed to build based on cgo based Pulsar client but we have switched to native go.

Thanks for your contribution.

Ming

**Comment by Pixelartist** [comment]
Thanks for the explanation @zzzming . I opened a [pull request](https://github.com/kafkaesque-io/pulsar-beam/pull/59) - sadly, the test fails with the reason "Please provide an upload token from codecov.io with valid arguments"

**Comment by zzzming** [comment]
Thanks! It's merged.

I explained the problem in the PR.  https://github.community/t/make-secrets-available-to-builds-of-forks/16166/20

I have to redesign unit test and integration test to work around this problem, by not using Github secrets for actions.
